### ISSUE TITLE
Compilation error: dLUstruct_gpu_t missing ijb_lookupVec and ijb_lookupPtr

### ISSUE THREAD

**Issue by pwxy** [xiaoyeli/superlu_dist#142]
Current version of master (SHA b64fe36) is failing to compile with gcc 11.2.0 on Perlmutter with the following error:

superlu_dist/SRC/dsuperlu_gpu.cu(804): error: class "dLUstruct_gpu_t" has no member "ijb_lookupVec"
superlu_dist/SRC/dsuperlu_gpu.cu(805): error: class "dLUstruct_gpu_t" has no member "ijb_lookupPtr"

In dsuperlu_gpu.cu, have the following:

800	checkGPU(gpuFree(A_gpu->jib_lookupVec));
801	checkGPU(gpuFree(A_gpu->jib_lookupPtr));
	checkGPU(gpuFree(A_gpu->local_u_blk_infoVec));
	checkGPU(gpuFree(A_gpu->local_u_blk_infoPtr));
804	checkGPU(gpuFree(A_gpu->ijb_lookupVec));
805	checkGPU(gpuFree(A_gpu->ijb_lookupPtr));

Lines 804+805 were added in the commit SHA c8da05d on Sat Apr 22.

Looks like there is both ijb_* and jib_* lookupVec and lookupPtr, but dlustruct_gpu.h defines only the jib_*

**Comment by xiaoyeli** [comment]
@pwxy Thanks. Resolved.
